### ISSUE TITLE
Image broken on Atom.io

### ISSUE THREAD

**Issue by Alhadis** [dlmanning/language-ohm#1]
<img src="https://cloud.githubusercontent.com/assets/2346707/16682458/2387f33c-453e-11e6-8379-cc980a24891a.png" width="375" alt="Figure 1" />

Don't worry, I've been [bitten](https://github.com/Alhadis/language-apl/commit/076c57eb9) by this too. Atom.io can't stomach images with relative URLs yet, so the screenshot's URL needs to be given in full:

``` markdown
![Screenshot](!https://media.githubusercontent.com/media/dlmanning/language-ohm/master/screenshot.png)
```

It's a known issue with Atom.io.

**Comment by dlmanning** [comment]
@Alhadis : Thanks! Was just looking into how to fix this.

**Comment by Alhadis** [comment]
BTW, you'll need to push another release in order for the changes to be reflected on Atom.io... =)
